### ISSUE TITLE
[docs] : 질문_Git flow중 push 관련 질문

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC2-Team13-RnB#10]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/103012763/172136382-fe6bb8c3-6cc9-4e22-9d18-2caed2d0d241.png">
레이가 노션에 정리해주신 git flow중, 4번 항목에 관한 질문입니다.  

저는 현재 remote에서 origin/main, origin/dev를 가져와서 local에서 dev로부터 Ground/StagePaging 브랜치를 생성하여 작업하고 있었습니다.  
해당 브랜치에서의 add, commit을 완료하였고, 이제 push를 하려 하는데, 여기서 push를 어디로 하면 되나요?  

1. remote에 있는 origin/main (이건 절대 아니겠죠?). 
2. remote에 있는 origin/dev. 
3. remote에 없지만 이제 만들면 되는 origin/Ground/StagePaging

(위에서 계속 origin 이라는 단어를 붙이는데, 이는 xcode에서 remote에 있는 브랜치를 origin/ 을 붙여서 표기하길래 그렇게 한 것입니다.)
<img width="263" alt="image" src="https://user-images.githubusercontent.com/103012763/172137001-7dbc1469-0a4c-4d49-a472-f82c62f52332.png">

**Comment by moonjs0113** [comment]
``` shell
$ git push origin Ground/StagePaging
```
가 맞습니다.

git remote add 시에 
``` shell
git remote add {로컬에서_부를_Git_Repository의_의름} https://github.com/~~
```
라고 진행하셨을 겁니다!

따라서 origin은 그라운드의 Local에서 Git Repository를 부르는 이름입니다.

위 명령어를 해석해보면
Ground/StagePaging라는 브랜치를 origin이라는 git repository에 push(업로드) 하겠다 라는 의미가 됩니다.

**Comment by GroundDev** [comment]
아하! 그렇군요 바로 Dev로 push하는게 아니군요
감사합니다 레이

+)
제가 클론 해오는건 GitHub Desktop으로 진행하였다보니 git remote add 명령어는 몰랐네요. 공부해볼게요
