### ISSUE TITLE
[question] : 가로모드 방향에 관하여

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC2-Team13-RnB#11]
저희 세로모드와 가로모드 사이의 이동은 강제하기로 하였던것으로 기억합니다.  
근데 가로모드 중에서 어떤 방향으로 할지도 현재 정해진 상황인가요?  
<img width="953" alt="image" src="https://user-images.githubusercontent.com/103012763/172141145-dd404484-cebe-4c30-a54d-4331294c2119.png">
.landscapeRight 인가요 .landscapeLeft인가요 아니면 이 둘 중 어느 가로모드로 할 지는 사용자가 선택할 수 있게(즉 반응형으로) 하나요?

**Comment by moonjs0113** [comment]
우선적으로 나온것은 `. landscapeRight` 입니다.

**Comment by GroundDev** [comment]
사용자가 강제로 `.landscapeRight`를 통해 화면이 강제로 가로모드로 전환되는데, 이때 사용자가 `.landscapeLeft`로 아이폰을 돌릴 일은 없을것이라 예상되어서, 개발할 때는 `.landscapeRight`만 고려해서 해도 될 듯 합니다.
