### ISSUE TITLE
[question] : 가로모드 시 status bar는 원래 없는게 default인가요?

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC2-Team13-RnB#21]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/103012763/172566469-cd01b571-a0fb-4255-9d5a-d17d1cc77a26.png">
가로모드(영어로는 landscape)일 때 status bar가 어떻게 되어있는거지? 스케치를 확인해보니 저희는 위 아래는 없다고 가정하고 디자인을 한 듯 합니다.

https://stackoverflow.com/questions/65022240/ios-14-display-status-bar-in-landscape 

위에서
> Since iOS 8, status bar is hidden in landscape by default

라는 문구를 발견했는데, 이게 현재도 적용되는건지는 잘 모르겠더라고요.
제 아이폰에는 landscape mode인 앱은 게임밖에 없는데(와일드 리프트입니다!), 다른 분들은 이 landscape mode일때의 status bar가 있는 앱을 써보신 적이 있으신가요?

**Comment by moonjs0113** [comment]
놀라운 발견입니다! lanlandscape mode 일땐 정말 Status bar가 보이지 않네요!
사파리, 카카오톡 확인했습니다!
