### ISSUE TITLE
[docs] : 질문_conflict을 최소화 하기 위해선 무엇을 해야할까요?

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC2-Team13-RnB#3]
깃헙에 대해 공부하면서 다음과 같은 flow를 공부하게 되었습니다. 
(출처 : https://blog.naver.com/PostView.naver?blogId=codeitofficial&logNo=221938658754&redirect=Dlog&widgetTypeCall=true&directAccess=false)
1. 어떠한 공통된 커밋으로부터 두 개의 브랜치를 생성했습니다(A 브랜치, B 브랜치라고 하죠).
2. A 브랜치에서 sample.swift파일에 Text("리듬을 탄다")라고 작성하고 커밋했습니다.
3. B 브랜치에서 sample.swift파일에 같은 부분에 Text("춤을 춘다")라고 작성하고 커밋했습니다.
4. HEAD는 현재 A 브랜치에 있다고 합시다.
5. 이 상태에서
```
git merge B
```
를 하게 되면 conflict이 발생하게 됩니다.
6. 간단한 해결책은 단순히 merge를 취소하는겁니다.
```
git merge --abort
```
하지만 이게 해결책은 아니겠죠?
7. 그래서 conflict이 발생한 sample.swift파일을 열어서 conflict이 발생하지 않도록 수정해야합니다(이 부분이 어떻게 이루어진다는 것인지는 아직 잘 감이 오지 않네요).

질문은 이겁니다. **이렇게 conflict이 발생할 만한 상황을 처음부터 방지할 수 있을까요?**
예를 들어, sample1.swift파일은 Ground만 다루도록 하고, sample2.swift는 Haru만 다루도록 하는 식으로 미리 정해두면 방지할 수 있을까요?
혹은 위와 같은 방안으로 하게 되었을때의 단점이 있을까요?

**Comment by moonjs0113** [comment]
프로젝트의 규모와 진행 시점에 따라 다양한 해결책이 존재한다고 생각합니다.

우선 우리의 프로젝트를 기준으로 생각해봅시다. (규모: 작음, 진행 시점: 프로젝트 시작점)
우리의 프로젝트는 MVP 단계부터 개발을 시작하기에 화면당 기능의 수가 많지 않은 편입니다.
따라서 한 사람당 한 화면을 개발하는 방법이 Confict를 최소화할 수 있는 방안이라 생각합니다.

하지만, 두 명이 첫 화면(생선 선택 화면)를 작업하며, 한명은 UI, 한명은 기능에 대한 구현을 한다고 가정한다면 다음과 같은 작업 플로우가 예상됩니다.

UI 개발자는 UI에 대한 개발만 진행합니다.
이때 새로운 변수의 생성을 최소화 하여 작업합니다.
Text의 값도 하드코딩(하나씩 값을 직접 타이핑 ex. Text("광어") )으로 넣어줍니다.
텍스트, 버튼의 크기, Padding 등에 집중하여 작업이 될겁니다.

기능 개발자는 View에 대한 ViewModel을 개발합니다. (Model 정의가 필요하다면 Model까지)
(ViewModel: View에서 사용되는 값과 실행되는 기능을 관리하는 객체)
첫 화면에서는
1. 우리가 정의한 생선의 데이터를 가져오고 -> 값과 기능
2. 그 중 하나의 생선을 선택할 경우 그 값을 저장하고, -> 기능
3. 화면 전환을 위해 생선이 선택되었다는 것을 인식하는 값 -> 값
이 필요하겠군요.

그렇다면 이제 ViewModel에 이 모든 것들을 넣습니다.
``` swift
ex)
class ViewModel: ObservableObject {
    @Published var isSelectFish: Bool
    @Published var selectedFish: String
    @Published var fishList: [String]
    
    func getFishList() -> [String] {
        // Code
    }
}
```
이렇게 작성한다면 UI개발과는 별도로 기능에 대한 개발이 진행될 수 있으며,
작업 중인 UI와 별개의 View(다른 파일)를 통해서 해당 ViewModel을 테스트할 수도 있습니다.

**Comment by GroundDev** [comment]
고마워요 레이!
제가 처음에 말했듯이 하나의 화면을 한명이 전담하는 구조로도 가능하겠고
혹은 레이가 두번째 안으로 말씀해주셨듯이 하나의 화면을 한명은 UI, 한명은 기능구현을 담당하는 방식으로도 가능하겠네요
또 다른 협업방식도 존재하겠구요
그런데 이렇게 conflict이 일어나지 않도록 분리해서 함에도 풀리퀘하고 merge하면 conflict이 발생하는 이유가 무엇일까요?

**Comment by moonjs0113** [comment]
첫번째 요인은 UI와 기능들의 높은 의존도가 있겠네요.
A와 B라는 추가 작업을 위해서 기존에 있던 C라는 부분을 건드려야하는 상황이라면 문제가 발생하겠지요.
결국 A,B는 C라는 부분이 의존도가 있다는 의미인데, 애초에 A와 B를 작업할때 C로부터 독립적이도록 만든다면 conflict가 일어날 확률이 줄어들겠죠.

두번째 요인은 불가피한 상황인데요.
첫번째 요인 상황에 C라는 부분이 원래없었고 새로 만들어야하는 상황이라면, A작업자는 C-a를 만들고 B 작업자는 C-b를 만들겠죠 이때 직접적인 conflict는 생기지 않지만 결국 다른 기능이 있는 C파일이 두개가 되어 개념적인 Conflict가 발생하게 됩니다.

새번짜 요인은 규칙을 실수한 개발자 요인이 있겠네요!

**Comment by moonjs0113** [comment]
역할과 UI 기능을 나누는 과정이 중요한 이유입니다!

**Comment by GroundDev** [comment]
그래서 레이가 노션에 백로그 만들어두신 것처럼 애초부터 구현해야할 UI는 뭐가 있을지 기능은 뭐가 있을지를 세세히 명시한 상태로 프로젝트를 시작해야 하는 거군요. 감사합니다 레이!
