### ISSUE TITLE
[feat] : View 1차 연결

### ISSUE THREAD

**Issue by moonjs0113** [DeveloperAcademy-POSTECH/MC2-Team13-RnB#56]
내용
- View 1차 연결
- 손질방법선택 -> 기능 안내 페이지 전환 구현

**Comment by GroundDev** [comment]
@moonjs0113 레이 혹시 제가 작업하던 #55 내용이 여기로 합쳐진건가요?
#56 커밋을 살펴봤는데, 여기 보면 State 변수들이 추가로 선언은 되었으나 아직 구체적으로 어떤 식으로 연결되는지는 나와있지 않더라고요
노션에 있는 백로그에 제가 작업하던 파트가 사라져있어 혹시 이 이슈로 합쳐진건가 해서 여쭤봅니다

**Comment by moonjs0113** [comment]
#56에는
가로모드 안내 Alert을 위한 Bool변수와
다음페이지로 넘어가기 위해 NavigationLink를 활성화시키는 Bool변수가 추가되었습니다

**Comment by moonjs0113** [comment]
노션에서 사라진 백로그는 저도 어떤 백로그인지 알 수 없어서 아니면 제가 실수로 지웠을 수도...
어떤 백로그인지 아시면 추가해주시면 됩니다

**Comment by GroundDev** [comment]
아 **노안이슈가 다시 발생했습니다** 지운게 아니라 제가 다 안본거였네요!
View간에 이동을 해야하다보니 제가 임의로 레이가 작성했던 코드를 약간 수정해보고 있었습니다.
그래서 아마 이 #56 과 conflict이 발생하지 않을까 싶네요! 좀 이따 코드 스크럼때 끙끙거려보겠습니다ㅎㅎ
