### ISSUE TITLE
[question] : Branch 별로 merge, no-merge가 다르게 나타나는 이유?

### ISSUE THREAD

**Issue by GroundDev** [DeveloperAcademy-POSTECH/MC2-Team13-RnB#7]
현재 제 로컬에는 main, Dev 브랜치가 있는 상황입니다.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/103012763/172116130-bb06b010-33ad-400a-971f-8287dfda4f98.png">
main 브랜치로 checkout되어 있을때는 merge되지 않은 브랜치가 없다고 하는데,
Dev 브랜치로 checkout되어 있을때는 main이 merge되어 있지 않다고 합니다.
??? merge가 됐느냐 안됐느냐가 브랜치마다 다르게 볼수도 있는건가요? 아니면 제가 아직 이 merge개념이 완벽하게 숙지되지 않아서 헷갈리는 걸까요?

**터미널**
```
kimjs@KimJSs-MacBook-Pro MC2-Team13-RnB % git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
kimjs@KimJSs-MacBook-Pro MC2-Team13-RnB % git branch --merged
  Dev
* main
kimjs@KimJSs-MacBook-Pro MC2-Team13-RnB % git branch --no-merged
kimjs@KimJSs-MacBook-Pro MC2-Team13-RnB % git switch Dev
Switched to branch 'Dev'
Your branch is up to date with 'origin/Dev'.
kimjs@KimJSs-MacBook-Pro MC2-Team13-RnB % git branch --merged
* Dev
kimjs@KimJSs-MacBook-Pro MC2-Team13-RnB % git branch --no-merged
  main
```

**Comment by GroundDev** [comment]
혹은, 현재 Dev가 main에 비해 1 commit behind이기 때문인걸까요?
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/103012763/172116825-d801d82a-41f4-4fb6-8edd-397d88e42f8f.png">

**Comment by GroundDev** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/103012763/172117820-f34e6847-eea3-4c37-8643-a134ef173dee.png">

pull request #6 를 보면, 브랜치 Rey가 브랜치 main으로 merge되었다고 하지만, 브랜치 Dev를 거치지는 않은 건가요?
다음은 소스트리로 본 화면입니다.
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/103012763/172117715-8861b212-1b30-4e59-8fe3-9577f0dc0af6.png">

**Comment by moonjs0113** [comment]
네 프로젝트 생성을 Dev를 거치지 않고 main에 바로 진행했습니다.

**Comment by GroundDev** [comment]
앗 그렇다면 제가 로컬에서 작업할 때 Dev 브랜치로부터 생성하는게 아니라 main으로부터 생성해야 했던 건가요?

**Comment by moonjs0113** [comment]
Rey -> Merge main -> main checkout dev 순으로 작성되었기 때문에 문제없습니다.
(dev가 main으로부터 생성된 브랜치)

**Comment by moonjs0113** [comment]
**merge가 됐느냐 안됐느냐가 브랜치마다 다르게 볼수도 있는건가요? -> 네**
`--merged`와 `--no-merged`는 현재 위치한 브랜치로부터 다른 브랜치의 Merge 상태를 추적합니다.

소스 트리 사진에서 보듯
main 입장에서 Dev와 자신은 이미 자신의 위치에서 merge된 브랜치가 됩니다.
그러니 자연스럽게 merge되지 않은`--no-merged` 브랜치가 없다고 표시됩니다.

Dev 입장에서 보았을 때는 자신은 당연히 merge된 브랜치가 되고,
하나의 커밋을 앞서고 있는 main은 아직 자신에게 merge되지 않은 브랜치로 인식하게 됩니다.

**Comment by GroundDev** [comment]
> Rey -> Merge main -> main checkout dev 순으로 작성되었기 때문에 문제없습니다.
> (dev가 main으로부터 생성된 브랜치)

저는 레이가 현재 프로젝트생성을 하여 그걸 기반으로 다른 팀원들이 작업해야한다고 생각했습니다.
그래서 그러한 프로젝트생성이 반영된 브랜치를 가져와야한다고 생각하는데요,
말씀하신대로 Rey 브랜치가 main으로 merge된 것은 보이나, Dev는 main에 비해 커밋이 뒤쳐지고 있습니다.
그렇다면 레이가 기초로 만들어둔 프로젝트생성이 Rey 브랜치에 있는 상황에서 Dev 브랜치를 건너뛰고 main 브랜치로 갔다면은,
Dev는 현재 레이가 만든 프로젝트생성이 반영되지 않은 상태인 브랜치가 아닌가요?
위에 언급해주신 Rey -> Merge main -> ... 이 부분이 답변이 될 것 같은데, 혹시 좀 더 상세히 설명해주실 수 있을까요?

**Comment by GroundDev** [comment]
답변 : 최초로 main에서 Rey 브랜치로 checkout하여 프로젝트를 생성한 이후, 이 브랜치에서 Dev 브랜치를 checkout 하고 또한 Rey 브랜치는 main으로 merge하였다고 합니다. 즉, 현재 main 브랜치와 Dev 브랜치의 내용은 차이가 없었으며(현재는 커밋이 몇번 앞서있으나, 아직 개발 초기라서 이 점때문에 나타나는 conflict은 쉽게 조정할 수 있을 것으로 기대됩니다) 이에 최초로 remote의 깃헙으로부터 로컬로 받을때는 Dev 브랜치를 받으시면 됩니다. (기본적으로, 현재 작업 초기라서 main이든 Dev든 최초 다운받는 브랜치가 무엇이든 큰 문제는 되지 않습니다)
